config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root "contractors#cool"
  get '/signup' => 'contractors#new'
  post '/contractors' => 'contractors#create'
  resources :contractors do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contractor.rb
class Contractor < ApplicationRecord
    has_secure_password
    has_many :tasks, dependent: :destroy
    validates :name, presence: true
    validates :address, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :contractor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

  def current_user
    @current_user ||= Contractor.find(session[:contractor_id]) if session[:contractor_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
    before_action :authorize

    def cool

    end
    def index
        @contractors = Contractor.all
        @tasks = Task.all
    end
    def login
        @contractor = Contractor.first
    end
    def show
        @contractor = Contractor.find(params[:id])
    end
    def new
        # @contractor = Contractor.new
    end
    def create
        # @contractor = Contractor.create(contractor_params)
        # if @contractor.save
        #     flash[:notice] = "Contratulations for creating yourself as a contractor"
        #     redirect_to @contractor
        # else
        #     flash[:notice] = "Sorry please try again..."
        #     render :new, status: :unprocessable_entity
        # end
        @contractor = Contractor.new(contractor_params)
        if contractor.save
            session[:contractor_id] = contractor.id
            redirect_to '/'
        else
            redirect_to '/signup'
        end
    end
    def edit
        @contractor = Contractor.find(params[:id])
    end
    def update
        @contractor = Contractor.find(params[:id])

        if @contractor.update(contractor_params)
            flash[:notice] = "Updating Profile Sucessfully"
            redirect_to @contractor
        else
            redirect_to :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @contractor = Contractor.find(params[:id])
        @contractor.destroy

        redirect_to root_path, status: :see_other
    end
    private
    def contractor_params
        params.require(:contractor).permit!
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @contractor = Contractor.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if contractor && contractor.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:contractor_id] = contractor.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:contractor_id] = nil
    redirect_to '/login'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @contractor = Contractor.find(params[:contractor_id])
        @task = @contractor.tasks.create(task_params)
        puts @task
        redirect_to contractor_path(@contractor)
    end

    def destroy
        @contractor = Contractor.find(params[:contractor_id])

        @task = @contractor.tasks.find(params[:id])
        
        @task.destroy
        
        redirect_to contractor_path(@contractor), status: :see_other
    end

    private
    def task_params
        params.require(:task).permit(:category,:description,:amount,:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/contractors/_form.html.erb
<%= form_with model: @contractor do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @contractor.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :mobileno %><br>
      <%= form.text_field :mobileno %>
    </div>

    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %>
    </div>

    <div>
      <%= form.label :status %><br>
      <%= form.select :status ,["Active","Deactive"]%>
    </div>

    <div>
      <%= form.label :address %><br>
      <%= form.text_area :address %>
      <% @contractor.errors.full_messages_for(:address).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :city %><br>
      <%= form.text_field :city %>
    </div>

    <div>
      <%= form.label :pincode %><br>
      <%= form.text_field :pincode %>
    </div>

    <div>
      <%= form.label :state %><br>
      <%= form.text_field :state %>
    </div>

    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/contractors/edit.html.erb
<h1>Edit Details</h1>

<%= render "form"%>

app/views/contractors/login.html.erb
<h1>Hiii...</h1>

app/views/contractors/new.html.erb
<h1>New Contractor</h1>

<%= render "form"%>


<h1>Signup!</h1>

<%= form_for :contractor, url: '/contractors' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

app/views/contractors/show.html.erb
<h1>Current Contractor Details</h1>

<h2>Name: <%= @contractor.name %> 
  <% if @contractor.status == "Active"%>
  <span style="color:green;">
    <%= @contractor.status %>
  </span>
  <%else%>
  <span style="color:red;">
    <%= @contractor.status %>
  </span>
  <%end%>
</h2>




<ul>
  <li><%= link_to "Edit", edit_contractor_path(@contractor) %></li>
  <li><%= link_to "Delete", contractor_path(@contractor), data: {
            turbo_method: :delete,
            turbo_confirm: "Click OK to Delete"
  }%></li>
</ul>

<h2>Previously Added Tasks</h2>
<%= render @contractor.tasks %>


<h2>Add a new Tasks:</h2>
<%= render "tasks/form"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiceFinal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ @contractor, @contractor.tasks.build ] do |form| %>
    <p>
      <%= form.label :category %><br>
      <%= form.select :category ,["plumber","electrician"]%>
    </p>
    <p>
    <%= form.label :status %><br>
    <%= form.select :status,["ACTIVE","DEACTIVE"] %>
    </p>
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
    <p>
      <%= form.label :amount %><br>
      <%= form.text_field :amount %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/tasks/_task.html.erb
<% if task.status == "ACTIVE"%>
<div style="color:green;font-size:larger">
    <p>
      <strong>Category:</strong>
      <%= task.category %>
    </p>
    
    <p>
      <strong>Description:</strong>
      <%= task.description %>
    </p>
  
    <p>
    <strong>Amount:</strong>
    <%= task.amount %>/-
  </p>
  <p>
    <%= link_to "Destroy Task", [task.contractor, task], data: 
    {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
 </div>  
<% else %>
  <div style="color:red">
  <p>
    <strong>Category:</strong>
    <%= task.category %>
  </p>
  
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
  <strong>Amount:</strong>
  <%= task.amount %>/-
</p>
<p>
  <%= link_to "Destroy Task", [task.contractor, task], data: 
  {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
</p>
</div> 
<%end%>